Repository opensrp/opensrp-client-native-form, pull requests merged in 2020-07, with the labels that each got.

#447 Testing Tuesday
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/activities/MultiLanguageActivity.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/widgets/BasicRDTCaptureFactory.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/widgets/NumberSelectorFactory.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/widgets/RDTCaptureFactory.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/widgets/BasicRDTCaptureFactoryTest.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/widgets/NumberSelectorFactoryTest.java
Labels: Testing Tuesday

#446 Add CumulativeTotalValidator tests
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/validators/edittext/CumulativeTotalValidator.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/validators/edittext/CumulativeTotalValidatorTest.java
Labels: Testing Tuesday

#451 Add Form tests
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/domain/FormTest.java
Labels: Testing Tuesday

#452 Adding the repeating groups tests
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/widgets/RepeatingGroupFactory.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/widgets/RepeatingGroupFactoryTest.java
Labels: Testing Tuesday

#453 Use client form version as form version
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/utils/FormUtils.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/utils/FormUtilsTest.java
  gradle.properties
Labels: Form Configuration

#455 Add tests
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/domain/WidgetMetadata.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/domain/WidgetArgsTest.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/domain/WidgetMetadataTest.java
Labels: Testing Tuesday

#457 Validate before casting
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/fragments/JsonFormFragment.java
  gradle.properties
Labels: enhancement

#458 Add unit tests
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/comparisons/RegexComparison.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/utils/FormUtils.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/utils/Utils.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/customviews/ToasterLinearLayoutTest.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/utils/ExObjectResultTest.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/utils/UtilsTest.java
Labels: Testing Tuesday
