Repository opensrp/opensrp-client-native-form, pull requests merged in 2020-03, with the labels that each got.

#375 Testing Tuesday Week 3
  .travis.yml
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/TestConstants.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/activities/JsonFormBarcodeScanActivityTest.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/presenters/JsonFormFragmentPresenterRoboElectricTest.java
  gradle/wrapper/gradle-wrapper.properties
Labels: Testing Tuesday

#376 Testing Tuesday 3
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/utils/FormUtils.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/utils/FormUtilsTest.java
  sample/src/main/assets/json.form/sub_form/child_enrollment_sub_form.json
Labels: Testing Tuesday

#380 Rule engine factory test
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/rules/RulesEngineFactoryTest.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/utils/MultiSelectListUtilsTest.java
Labels: Testing Tuesday

#381 Testing Tuesday
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/utils/FormUtils.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/activities/JsonFormActivityTest.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/utils/FormUtilsTest.java
Labels: Testing Tuesday

#379 TT wk JsonFormFragmentPresenter tests
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/TestConstants.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/presenters/JsonFormFragmentPresenterRoboElectricTest.java
Labels: Testing Tuesday

#373 Add MLS to native forms
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/activities/JsonFormBaseActivity.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/constants/JsonFormConstants.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/interactors/JsonFormInteractor.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/interfaces/FormWidgetFactory.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/utils/NativeFormLangUtils.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/utils/Utils.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/utils/NativeFormLangUtilsTest.java
  android-json-form-wizard/src/test/resources/form_strings_en_US.properties
  android-json-form-wizard/src/test/resources/form_strings_in.properties
  android-json-form-wizard/src/test/resources/test_form_translation_en_US
  android-json-form-wizard/src/test/resources/test_form_translation_in
  android-json-form-wizard/src/test/resources/test_form_translation_interpolated
  android-json-form-wizard/src/test/resources/test_form_translation_interpolated_missing_translations
  android-json-form-wizard/src/test/resources/test_yaml_translation_en_US
  android-json-form-wizard/src/test/resources/test_yaml_translation_interpolated
  android-json-form-wizard/src/test/resources/test_yaml_translation_interpolated_missing_translations
  android-json-form-wizard/src/test/resources/yaml_strings_en_US.properties
  gradle.properties
  sample/src/main/java/org/smartregister/nativeform/MainActivity.java
  sample/src/main/resources/anc_register_en_US.properties
  sample/src/main/resources/anc_register_fr.properties
Labels: enhancement

#384 TT Week 4 Json Form Fragment Presenter unit tests
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/presenters/JsonFormFragmentPresenter.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/utils/FormUtils.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/utils/ImageUtils.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/presenters/JsonFormFragmentPresenterRoboElectricTest.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/shadow/ShadowContextCompat.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/shadow/ShadowPermissionUtils.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/utils/zing/FormUtilsTest.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/utils/zing/ImageUtilsTest.java
Labels: Testing Tuesday

#385 Tt form utils test
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/utils/FormUtilsTest.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/utils/UtilsTest.java
Labels: Testing Tuesday

#386 testing tuesday
  android-json-form-wizard/src/main/assets/json.form/sub_form/expansion_panel_sub_form.json
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/utils/FormUtilsTest.java
Labels: Testing Tuesday

#395 Remove an unwanted url paste on the DatePickerFactory
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/widgets/DatePickerFactory.java
  gradle.properties
Labels: bug
