Repository opensrp/opensrp-client-native-form, pull requests merged in 2020-02, with the labels that each got.

#356 :bug: Fix java8 compatibility issues
  android-json-form-wizard/build.gradle
  gradle.properties
  sample/build.gradle
Labels: bug

#359 Update the expansion panel content view
  android-json-form-wizard/build.gradle
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/utils/FormUtils.java
  gradle.properties
Labels: enhancement

#362 Bump lib versions
  android-json-form-wizard/build.gradle
  gradle.properties
Labels: enhancement

#363 Fix Unit test coverage reporting
  .travis.yml
  android-json-form-wizard/build.gradle
  build.gradle
Labels: Testing Tuesday

#366 Feature/dubdabasoduba tt 1 issue 364
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/utils/FormUtils.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/widgets/CheckBoxFactory.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/widgets/DatePickerFactory.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/widgets/EditTextFactory.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/widgets/ExtendedRadioButtonWidgetFactory.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/widgets/LabelFactory.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/widgets/NativeRadioButtonFactory.java
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/widgets/SpinnerFactory.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/widgets/ExpansionPanelWidgetFactoryTest.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/widgets/NativeRadioButtonFactoryTest.java
Labels: Testing Tuesday

#365 Add json form fragment presenter tests
  android-json-form-wizard/src/main/java/com/vijay/jsonwizard/presenters/JsonFormFragmentPresenter.java
  android-json-form-wizard/src/test/java/com/vijay/jsonwizard/presenters/JsonFormFragmentPresenterTest.java
Labels: Testing Tuesday
